#!/bin/bash

set -euC
# set -o pipefail

# exec 5>> /tmp/xmosh/shell-script-debug.out
# BASH_XTRACEFD="5"
# PS4='$LINENO: '
# set -x

cd "$(dirname "$(readlink "$0")")"

exec npx github-copilot-cli "$@"
